apiVersion: run.ai/v2alpha1
kind: DistributedWorkload
metadata:
  annotations:
    runai-cli-version: 2.11.11
  creationTimestamp: null
  labels:
    PreviousJob: "true"
  name: JOB_NAME_PLACEHOLDER
  namespace: runai-PROJECT_PLACEHOLDER
spec:
  command:
    value: sleep infinity
  gpu:
    value: "NUM_GPUS"
  cpu:
    value: "0.05"
  memory:
    value: 1Mi
  image:
    value: gcr.io/run-ai-lab/ubuntu:loop
  imagePullPolicy:
    value: IfNotPresent
  jobType: PyTorchJob
  name:
    value: JOB_NAME_PLACEHOLDER
  pyTorchJob:
    values: {}
  runPolicy:
    values:
      cleanPodPolicy:
        value: None
  workers:
    value: NUM_WORKERS_PLACEHOLDER
status: {}

